spring:
  application:
    name: CatRest
  datasource:
    url: jdbc:postgresql://localhost:5432/cat
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



server:
  port: 8080